#ifndef CONFIG_H
#define CONFIG_H

//Definitions for kernel heap virtual address space
#define KERNEL_HEAP_START_VIRTUAL_ADDRESS 0xD0000000 
#define KERNEL_HEAP_SIZE_MB                 16       
#define KERNEL_HEAP_MAX_VIRTUAL_ADDRESS (KERNEL_HEAP_START_VIRTUAL_ADDRESS + (KERNEL_HEAP_SIZE_MB * 1024 * 1024))


#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define KERNEL_END 0x10a000
#define PAGE_SIZE 0x1000
#define RZOS_TOTAL_INTERRUPTS 512

// 100MB heap size
#define RZOS_HEAP_SIZE_BYTES 104857600
#define RZOS_HEAP_BLOCK_SIZE 4096
#define RZOS_HEAP_ADDRESS 0x0300000 
#define RZOS_HEAP_TABLE_ADDRESS 0x00007E00

#define RZOS_SECTOR_SIZE 512

#define RZOS_MAX_FILESYSTEMS 12
#define RZOS_MAX_FILE_DESCRIPTORS 512

#define RZOS_MAX_PATH 108

#define RZOS_TOTAL_GDT_SEGMENTS 6

#define RZOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define RZOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define RZOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define RZOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END RZOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - RZOS_USER_PROGRAM_STACK_SIZE

#define RZOS_MAX_PROGRAM_ALLOCATIONS 1024
#define RZOS_MAX_PROCESSES 12

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#define RZOS_MAX_ISR80H_COMMANDS 1024

#define RZOS_KEYBOARD_BUFFER_SIZE 1024

#endif